### PR TITLE
Use docker-systemd-replacement and entrypoint

### PR DESCRIPTION
**Pull request by shane-axiom**
@kamermans Another option to consider for dealing with systemd openmanage. This uses a drop-in systemctl replacement designed for running systemd services inside Docker containers. Seems to work well and is much lighter weight than running real systemd:

https://github.com/gdraheim/docker-systemctl-replacement

Beyond that, it's just a matter of using an ENTRYPOINT script to start the Dell services using `srvadmin-services.sh start` before running other commands, and making sure that the ENTRYPOINT script has "systemd" in the first 16 characters of the command/script name so that the `srvadmin-services.sh` script thinks its running under systemd.

This needs more testing but it seems to be working. I just updated some firmware by running `dsu -q` directly instead of starting a daemonized container.

### CODE REVIEW

**Comment by shane-axiom** [comment]
BTW the systemctl replacement has the EUPL license, which should be compatible with many other licenses including GPL

**Comment by shane-axiom** [comment]
Forgot to mention, this approach doesn’t need the extra cgroups volume mounted.

**Comment by kamermans** [comment]
Very nice, thanks!  I'll take a look tonight, but it all sounds great.

**Comment by shane-axiom** [comment]
Closing in favor of https://github.com/kamermans/docker-openmanage/pull/10

**Pull request closed without merging**
